version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dmart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=dmart_db
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - DB_HOST=db
      - DB_PORT=5432
      - CORS_ALLOWED_ORIGINS=http://dmartselfcheckout.duckdns.org:3000
      - CSRF_TRUSTED_ORIGINS=http://dmartselfcheckout.duckdns.org:3000
    depends_on:
      - db

  frontend:
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://dmartselfcheckout.duckdns.org:8000/api
    environment:
      - NEXT_PUBLIC_API_URL=http://dmartselfcheckout.duckdns.org:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:




