# Generated by Django 6.1.1 on 2026-09-21 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('PAYMENT_SUCCESS', 'Payment Success'), ('RECEIPT_READY', 'Receipt Ready'), ('EXIT_QR_READY', 'Exit QR Ready'), ('EXIT_ALLOWED', 'Exit Allowed'), ('EXIT_REJECTED', 'Exit Rejected'), ('LOYALTY_EARNED', 'Loyalty Earned'), ('SECURITY_ALERT', 'Security Alert')], max_length=50)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('customer', 'order', 'notification_type'), name='unique_notification_per_order_type')],
            },
        ),
    ]
