# Generated by Django 6.1.1 on 2026-09-21 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=128, unique=True)),
                ('token_reference', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_token', to='orders.order')),
            ],
            options={
                'verbose_name': 'Exit Token',
                'verbose_name_plural': 'Exit Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
