# Generated by Django 6.1.1 on 2026-09-21 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_verification', '0001_initial'),
        ('orders', '0002_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('ALLOWED', 'Allowed'), ('REJECTED', 'Rejected')], max_length=20)),
                ('rejection_reason', models.CharField(blank=True, choices=[('INVALID_TOKEN', 'Invalid Token'), ('TOKEN_EXPIRED', 'Token Expired'), ('TOKEN_ALREADY_USED', 'Token Already Used'), ('TOKEN_REVOKED', 'Token Revoked'), ('ORDER_NOT_FOUND', 'Order Not Found'), ('PAYMENT_NOT_COMPLETED', 'Payment Not Completed'), ('ORDER_MISMATCH', 'Order Mismatch'), ('INVALID_QR_FORMAT', 'Invalid QR Format'), ('UNAUTHORIZED', 'Unauthorized'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exit_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='exit_verification.exittoken')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_verifications', to='orders.order')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exit Verification',
                'verbose_name_plural': 'Exit Verifications',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
