# Generated by Django 6.1.1 on 2026-09-21 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_verification', '0002_exitverification'),
        ('orders', '0002_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('INVALID_QR', 'Invalid QR'), ('INVALID_TOKEN', 'Invalid Token'), ('EXPIRED_TOKEN_ATTEMPT', 'Expired Token Attempt'), ('USED_TOKEN_ATTEMPT', 'Used Token Attempt'), ('REVOKED_TOKEN_ATTEMPT', 'Revoked Token Attempt'), ('PAYMENT_MISMATCH', 'Payment Mismatch'), ('ORDER_MISMATCH', 'Order Mismatch'), ('REPEATED_FAILURES', 'Repeated Failures'), ('UNAUTHORIZED_VERIFICATION', 'Unauthorized Verification'), ('OTHER', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exit_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to='exit_verification.exittoken')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspicious Activity',
                'verbose_name_plural': 'Suspicious Activities',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['activity_type'], name='exit_verifi_activit_08ecec_idx'), models.Index(fields=['severity'], name='exit_verifi_severit_fd7384_idx'), models.Index(fields=['status'], name='exit_verifi_status_8794e8_idx'), models.Index(fields=['detected_at'], name='exit_verifi_detecte_5b1962_idx'), models.Index(fields=['user'], name='exit_verifi_user_id_eb62d3_idx'), models.Index(fields=['order'], name='exit_verifi_order_i_cdce3e_idx'), models.Index(fields=['ip_address'], name='exit_verifi_ip_addr_17db70_idx')],
            },
        ),
    ]
