name: Debug Server

on:
  push:
    branches: [ debug ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Run Debug Commands on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd DMart-Self-Checkout-Smart-Exit-System
          sudo docker ps -a > ps.txt
          sudo docker compose logs --tail=200 backend > logs.txt
          curl -X POST -H "Content-Type: text/plain" --data-binary "@ps.txt" https://webhook.site/671b44de-2301-461d-bc33-bcf7eae6a307
          curl -X POST -H "Content-Type: text/plain" --data-binary "@logs.txt" https://webhook.site/671b44de-2301-461d-bc33-bcf7eae6a307
